name: test

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - run: go get github.com/gnoswap-labs/gno/gnovm/cmd/gno
      - run: go mod download -x
      - run: make test.integration